import Link from "next/link";
import "../globals.css";
import Loader from "@/components/Loader";
import { Suspense } from "react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav className={"navbar"}>
          <Link className={"navLink"} href={"/"}>
            Back Home
          </Link>
        </nav>
        <Suspense fallback={<Loader />}>{children}</Suspense>
      </body>
    </html>
  );
}
