import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Link from "next/link";
import { Suspense } from "react";
import Loader from "@/components/Loader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex-1">
          <nav className={"navbar"}>
            <Link className={"navLink"} href={"/"}>
              Home
            </Link>
            <Link className={"navLink"} href={"/car/new"}>
              Add new car
            </Link>
          </nav>
          <Suspense fallback={<Loader />}>{children}</Suspense>
        </main>
      </body>
    </html>
  );
}
